version: '2.1'
services:
    changedetection:
      build: .
      container_name: filelist-api-whitelist
      environment:
        - FL_USERNAME=your_username
        - FL_PASSWORD=your_password
        - CHECK_INTERVAL=10 # in minutes I suggest putting more than 5 minutes.
      restart: unless-stopped
